<?php
defined( 'ABSPATH' ) || exit;

final class AE_Admin {
	private static ?AE_Admin $instance = null;
	private const PAGE = 'apuracao-eleitoral';
	public static function instance(): AE_Admin { return self::$instance ??= new self(); }

	public function register(): void {
		add_action( 'admin_menu', array( $this, 'menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) );
		foreach ( array( 'quick_setup', 'save_contest', 'start_import', 'save_collection', 'retry_job', 'run_jobs' ) as $action ) { add_action( 'admin_post_ae_' . $action, array( $this, $action ) ); }
		add_action( 'wp_ajax_ae_admin_status', array( $this, 'ajax_status' ) );
	}

	public function menu(): void { add_menu_page( 'Apuração Eleitoral', 'Apuração', 'manage_options', self::PAGE, array( $this, 'page' ), 'dashicons-chart-bar', 58 ); }
	public function assets( string $hook ): void {
		if ( 'toplevel_page_' . self::PAGE !== $hook ) { return; }
		wp_enqueue_style( 'ae-admin', AE_URL . 'assets/css/ae-admin.css', array(), AE_VERSION );
		wp_enqueue_script( 'ae-admin', AE_URL . 'assets/js/ae-admin.js', array(), AE_VERSION, true );
		wp_localize_script( 'ae-admin', 'AEAdmin', array( 'ajaxUrl' => admin_url( 'admin-ajax.php' ), 'nonce' => wp_create_nonce( 'ae_admin_status' ) ) );
	}

	public function page(): void {
		$this->guard(); $tab = sanitize_key( $_GET['tab'] ?? 'overview' ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		if ( ! in_array( $tab, array( 'overview', 'setup', 'import', 'jobs', 'logs' ), true ) ) { $tab = 'overview'; }
		?><div class="wrap ae-admin"><div class="ae-title"><div><h1>Apuração Eleitoral</h1><p>Configure, importe e acompanhe a apuração sem sair do WordPress.</p></div><span class="ae-version">v<?php echo esc_html( AE_VERSION ); ?></span></div><?php $this->notice(); ?><nav class="nav-tab-wrapper"><?php foreach ( array( 'overview'=>'Visão geral', 'setup'=>'Configuração', 'import'=>'Importar e coletar', 'jobs'=>'Fila e progresso', 'logs'=>'Logs' ) as $key=>$label ) : ?><a class="nav-tab <?php echo $tab === $key ? 'nav-tab-active' : ''; ?>" href="<?php echo esc_url( $this->url( $key ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></nav><?php call_user_func( array( $this, 'tab_' . $tab ) ); ?></div><?php
	}

	private function tab_overview(): void {
		global $wpdb; $p = $wpdb->prefix . 'ae_'; $counts = array(
			'elections'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}elections"), 'contests'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}contests WHERE active=1"), 'candidates'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}candidates"), 'snapshots'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}snapshots WHERE status='valid'") ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$next = wp_next_scheduled( 'ae_run_jobs' );
		?><div class="ae-grid ae-stats"><?php foreach ( array( 'elections'=>'Eleições', 'contests'=>'Disputas ativas', 'candidates'=>'Candidatos', 'snapshots'=>'Snapshots válidos' ) as $key=>$label ) : ?><div class="ae-card"><strong><?php echo esc_html( number_format_i18n( $counts[$key] ) ); ?></strong><span><?php echo esc_html( $label ); ?></span></div><?php endforeach; ?></div>
		<div class="ae-grid ae-two"><section class="ae-panel"><h2>Comece em três passos</h2><ol class="ae-steps"><li><span>1</span><div><strong>Prepare a eleição</strong><p>Crie cargos, turnos, UFs e vagas automaticamente.</p><a class="button" href="<?php echo esc_url($this->url('setup')); ?>">Configurar</a></div></li><li><span>2</span><div><strong>Importe candidatos</strong><p>Cole a URL oficial do CSV, ZIP ou JSON do TSE.</p><a class="button" href="<?php echo esc_url($this->url('import')); ?>">Importar</a></div></li><li><span>3</span><div><strong>Ative a coleta</strong><p>Escolha disputa e frequência; o plugin cuida do restante.</p><a class="button button-primary" href="<?php echo esc_url($this->url('import')); ?>#ae-collection">Ativar coleta</a></div></li></ol></section>
		<section class="ae-panel"><h2>Saúde</h2><dl class="ae-health"><dt>Banco</dt><dd><span class="ae-dot ae-ok"></span> schema <?php echo esc_html((string)get_option('ae_schema_version','não instalado')); ?></dd><dt>Processador</dt><dd><?php echo $next ? '<span class="ae-dot ae-ok"></span> próximo ciclo em '.esc_html(human_time_diff(time(),$next)) : '<span class="ae-dot ae-bad"></span> cron não agendado'; ?></dd><dt>Último snapshot</dt><dd><?php echo esc_html((string)($wpdb->get_var("SELECT MAX(captured_at) FROM {$p}snapshots WHERE status='valid'") ?: 'ainda não recebido')); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared ?></dd></dl><?php $this->run_button(); ?></section></div><?php
	}

	private function tab_setup(): void {
		$elections = $this->elections( true );
		?><div class="ae-grid ae-two"><section class="ae-panel"><h2>Configuração rápida</h2><p>Um clique cria Presidente no Brasil, Governador por UF e Senador com duas vagas. O segundo turno é criado para Presidente e Governador.</p><form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><?php wp_nonce_field('ae_quick_setup'); ?><input type="hidden" name="action" value="ae_quick_setup"><label>Ano<input name="year" type="number" min="2022" max="2100" value="2026" required></label><label>Nome<input name="name" value="Eleições Gerais 2026" required></label><button class="button button-primary button-hero">Preparar eleição geral</button></form></section>
		<section class="ae-panel"><h2>Configuração existente</h2><?php if(!$elections): ?><p>Nenhuma eleição.</p><?php else: ?><table class="widefat striped"><thead><tr><th>Eleição</th><th>Status</th><th>Disputas</th></tr></thead><tbody><?php foreach($elections as $e): ?><tr><td><strong><?php echo esc_html($e->name); ?></strong><br><code><?php echo esc_html($e->slug); ?></code></td><td><?php echo esc_html($e->status); ?></td><td><?php echo esc_html((string)$e->contests); ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section></div>
		<section class="ae-panel"><h2>Adicionar disputa personalizada</h2><form class="ae-form-grid" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><?php wp_nonce_field('ae_save_contest'); ?><input type="hidden" name="action" value="ae_save_contest"><?php $this->election_select('election_id',$elections); ?><label>Turno<input name="round_no" type="number" min="1" max="3" value="1" required></label><label>Código do cargo<input name="position_code" value="0001" required></label><label>Nome do cargo<input name="position_name" placeholder="Presidente" required></label><label>Tipo<select name="scope_type"><option value="BR">Brasil</option><option value="UF">Estado</option><option value="MU">Município</option></select></label><label>Código<input name="scope_code" placeholder="BR ou ES" required></label><label>Abrangência<input name="scope_name" placeholder="Brasil ou Espírito Santo" required></label><label>Vagas<input name="seats" type="number" min="1" value="1" required></label><div><button class="button button-primary">Adicionar disputa</button></div></form></section><?php
	}

	private function tab_import(): void {
		global $wpdb; $p=$wpdb->prefix.'ae_'; $elections=$this->elections(); $contests=$wpdb->get_results("SELECT c.*,e.name election_name FROM {$p}contests c INNER JOIN {$p}elections e ON e.id=c.election_id WHERE c.active=1 ORDER BY e.year DESC,c.round_no,c.position_name,c.scope_code"); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		?><div class="ae-grid ae-two"><section class="ae-panel"><h2>1. Importar candidatos</h2><p>ZIP e CSV são processados em lotes, sem estourar a memória.</p><form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><?php wp_nonce_field('ae_start_import'); ?><input type="hidden" name="action" value="ae_start_import"><?php $this->election_select('election_id',$elections); ?><label>URL oficial do arquivo<input name="source_url" type="url" placeholder="https://dadosabertos.tse.jus.br/...zip" required></label><label>Formato<select name="format"><option value="auto">Detectar automaticamente</option><option value="zip">ZIP</option><option value="csv">CSV</option><option value="json">JSON</option></select></label><button class="button button-primary button-hero">Importar candidatos</button></form></section>
		<section id="ae-collection" class="ae-panel"><h2>2. Coleta automática</h2><p>A primeira coleta entra na fila imediatamente; as próximas são agendadas pelo plugin.</p><form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><?php wp_nonce_field('ae_save_collection'); ?><input type="hidden" name="action" value="ae_save_collection"><label>Disputa<select name="contest_id" required><option value="">Selecione...</option><?php foreach($contests as $c): ?><option value="<?php echo esc_attr($c->id); ?>"><?php echo esc_html($c->election_name.' · '.$c->position_name.' · '.$c->scope_code.' · '.$c->round_no.'º turno'); ?></option><?php endforeach; ?></select></label><label>Formato<select name="kind"><option>EA20</option><option>EA15</option><option>EA14</option></select></label><label>URL oficial do JSON<input name="source_url" type="url" placeholder="https://resultados.tse.jus.br/...json" required></label><label>Intervalo<select name="interval"><option value="30">30 segundos</option><option value="60" selected>1 minuto</option><option value="120">2 minutos</option><option value="300">5 minutos</option></select></label><label class="ae-check"><input type="checkbox" name="enabled" value="1" checked> Coleta recorrente ativa</label><button class="button button-primary button-hero">Salvar e iniciar coleta</button></form></section></div>
		<section class="ae-panel"><h2>Fontes configuradas</h2><table class="widefat striped"><thead><tr><th>Disputa</th><th>Formato</th><th>Intervalo</th><th>Situação</th></tr></thead><tbody><?php $configured=0; foreach($contests as $c): $config=json_decode((string)$c->config_json,true); $collection=$config['collection']??array(); if(empty($collection['source_url']))continue; $configured++; ?><tr><td><?php echo esc_html($c->position_name.' · '.$c->scope_code.' · '.$c->round_no.'º turno'); ?></td><td><?php echo esc_html($collection['kind']??''); ?></td><td><?php echo esc_html((string)($collection['interval']??60)); ?>s</td><td><span class="ae-status <?php echo !empty($collection['enabled'])?'is-completed':'is-paused'; ?>"><?php echo !empty($collection['enabled'])?'Ativa':'Pausada'; ?></span></td></tr><?php endforeach; if(!$configured): ?><tr><td colspan="4">Nenhuma fonte configurada.</td></tr><?php endif; ?></tbody></table></section><?php
	}

	private function tab_jobs(): void { ?><section class="ae-panel"><div class="ae-panel-head"><div><h2>Fila de processamento</h2><p>Atualização automática a cada cinco segundos.</p></div><?php $this->run_button(); ?></div><div id="ae-job-summary" class="ae-mini-stats"></div><div id="ae-jobs-table"><?php echo $this->jobs_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></section><?php }
	private function tab_logs(): void { global $wpdb; $table=$wpdb->prefix.'ae_logs'; $logs=$wpdb->get_results("SELECT * FROM {$table} ORDER BY id DESC LIMIT 100"); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		?><section class="ae-panel"><h2>Últimos eventos</h2><table class="widefat striped"><thead><tr><th>Data UTC</th><th>Nível</th><th>Evento</th><th>Contexto</th></tr></thead><tbody><?php foreach($logs as $log): ?><tr><td><?php echo esc_html($log->created_at); ?></td><td><span class="ae-status is-<?php echo esc_attr($log->level); ?>"><?php echo esc_html(strtoupper($log->level)); ?></span></td><td><code><?php echo esc_html($log->event); ?></code></td><td><details><summary>Ver detalhes</summary><pre><?php echo esc_html($log->context_json?:'{}'); ?></pre></details></td></tr><?php endforeach; if(!$logs): ?><tr><td colspan="4">Nenhum evento registrado.</td></tr><?php endif; ?></tbody></table></section><?php }

	public function quick_setup(): void {
		$this->verify('ae_quick_setup'); global $wpdb; $p=$wpdb->prefix.'ae_'; $year=max(2022,absint($_POST['year']??2026)); $slug='eleicoes-'.$year; $name=sanitize_text_field(wp_unslash($_POST['name']??'Eleições Gerais '.$year)); $now=current_time('mysql',true);
		$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$p}elections WHERE slug=%s",$slug)); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		if(!$id){$wpdb->insert($p.'elections',array('slug'=>$slug,'name'=>$name,'year'=>$year,'timezone'=>'America/Sao_Paulo','status'=>'active','config_json'=>'{}','created_at'=>$now,'updated_at'=>$now));$id=(int)$wpdb->insert_id;}else{$wpdb->update($p.'elections',array('name'=>$name,'status'=>'active','updated_at'=>$now),array('id'=>$id));}
		$items=array(array(1,'0001','Presidente','BR','BR','Brasil',1),array(2,'0001','Presidente','BR','BR','Brasil',1)); foreach($this->ufs() as $code=>$label){$items[]=array(1,'0003','Governador','UF',$code,$label,1);$items[]=array(2,'0003','Governador','UF',$code,$label,1);$items[]=array(1,'0005','Senador','UF',$code,$label,2);}
		foreach($items as $item){list($round,$position_code,$position_name,$scope_type,$scope_code,$scope_name,$seats)=$item;$external=$year.'-r'.$round.'-'.$position_code.'-'.$scope_code;$sql=$wpdb->prepare("INSERT INTO {$p}contests (election_id,external_id,round_no,position_code,position_name,scope_type,scope_code,scope_name,seats,active,config_json) VALUES (%d,%s,%d,%s,%s,%s,%s,%s,%d,1,'{}') ON DUPLICATE KEY UPDATE position_name=VALUES(position_name),scope_name=VALUES(scope_name),seats=VALUES(seats),active=1",$id,$external,$round,$position_code,$position_name,$scope_type,$scope_code,$scope_name,$seats);$wpdb->query($sql);} // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		AE_Logger::write('info','quick_setup_completed',array('election_id'=>$id,'year'=>$year,'contests'=>count($items)));$this->redirect('setup','Eleição preparada com '.count($items).' disputas.');
	}

	public function save_contest(): void { $this->verify('ae_save_contest'); global $wpdb; $table=$wpdb->prefix.'ae_contests'; $data=array('election_id'=>absint($_POST['election_id']??0),'round_no'=>max(1,absint($_POST['round_no']??1)),'position_code'=>sanitize_key(wp_unslash($_POST['position_code']??'')),'position_name'=>sanitize_text_field(wp_unslash($_POST['position_name']??'')),'scope_type'=>strtoupper(sanitize_key(wp_unslash($_POST['scope_type']??''))),'scope_code'=>strtoupper(sanitize_key(wp_unslash($_POST['scope_code']??''))),'scope_name'=>sanitize_text_field(wp_unslash($_POST['scope_name']??'')),'seats'=>max(1,absint($_POST['seats']??1)),'active'=>1,'config_json'=>'{}'); $data['external_id']='manual-'.$data['round_no'].'-'.$data['position_code'].'-'.$data['scope_code']; $wpdb->replace($table,$data); AE_Logger::write('info','contest_saved',array('contest_id'=>(int)$wpdb->insert_id));$this->redirect('setup','Disputa adicionada.'); }
	public function start_import(): void { $this->verify('ae_start_import');$format=sanitize_key($_POST['format']??'auto');$payload=array('election_id'=>absint($_POST['election_id']??0),'source_url'=>esc_url_raw(wp_unslash($_POST['source_url']??'')));if('auto'!==$format)$payload['format']=$format;if(!$payload['election_id']||!$payload['source_url'])$this->redirect('import','Preencha a eleição e a URL.','error');$id=AE_Job_Runner::enqueue('import_candidates',$payload);$this->redirect('jobs','Importação adicionada à fila. Job #'.$id.'.'); }
	public function save_collection(): void { $this->verify('ae_save_collection');global $wpdb;$table=$wpdb->prefix.'ae_contests';$id=absint($_POST['contest_id']??0);$contest=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id)); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		if(!$contest)$this->redirect('import','Disputa não encontrada.','error');$config=json_decode((string)$contest->config_json,true);if(!is_array($config))$config=array();$config['collection']=array('source_url'=>esc_url_raw(wp_unslash($_POST['source_url']??'')),'kind'=>strtoupper(sanitize_key($_POST['kind']??'EA20')),'interval'=>max(30,min(900,absint($_POST['interval']??60))),'enabled'=>!empty($_POST['enabled']));if(!$config['collection']['source_url'])$this->redirect('import','Informe a URL oficial do JSON.','error');$wpdb->update($table,array('config_json'=>wp_json_encode($config)),array('id'=>$id));if($config['collection']['enabled'])AE_Job_Runner::enqueue('collect_results',array('contest_id'=>$id,'kind'=>$config['collection']['kind'],'source_url'=>$config['collection']['source_url']));AE_Logger::write('info','collection_configured',array('contest_id'=>$id,'enabled'=>$config['collection']['enabled']));$this->redirect('import','Fonte salva e coleta atualizada.'); }
	public function retry_job(): void { $this->verify('ae_retry_job');global $wpdb;$id=absint($_POST['job_id']??0);$wpdb->update($wpdb->prefix.'ae_jobs',array('state'=>'retry','attempts'=>0,'run_after'=>current_time('mysql',true),'locked_until'=>null,'lock_token'=>null,'last_error'=>null),array('id'=>$id));$this->redirect('jobs','Job #'.$id.' recolocado na fila.'); }
	public function run_jobs(): void { $this->verify('ae_run_jobs');AE_Job_Runner::instance()->tick();$this->redirect('jobs','Fila processada manualmente.'); }
	public function ajax_status(): void { $this->guard();check_ajax_referer('ae_admin_status','nonce');global $wpdb;$table=$wpdb->prefix.'ae_jobs';$states=$wpdb->get_results("SELECT state,COUNT(*) total FROM {$table} GROUP BY state",OBJECT_K); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		wp_send_json_success(array('summary'=>array_map(static fn($row)=>(int)$row->total,$states),'html'=>$this->jobs_html())); }

	private function jobs_html(): string { global $wpdb;$table=$wpdb->prefix.'ae_jobs';$jobs=$wpdb->get_results("SELECT * FROM {$table} ORDER BY id DESC LIMIT 50");ob_start(); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		?><table class="widefat striped"><thead><tr><th>Job</th><th>Tipo</th><th>Situação</th><th>Progresso</th><th>Tentativas</th><th>Atualizado</th><th></th></tr></thead><tbody><?php foreach($jobs as $job):$cursor=json_decode((string)$job->cursor_json,true);?><tr><td>#<?php echo esc_html((string)$job->id);?></td><td><code><?php echo esc_html($job->type);?></code></td><td><span class="ae-status is-<?php echo esc_attr($job->state);?>"><?php echo esc_html($this->state_label($job->state));?></span><?php if($job->last_error):?><details><summary>Erro</summary><small><?php echo esc_html($job->last_error);?></small></details><?php endif;?></td><td><?php echo 'import_candidates'===$job->type?esc_html(number_format_i18n((int)($cursor['offset']??0)).' registros'):'—';?></td><td><?php echo esc_html((string)$job->attempts);?>/5</td><td><?php echo esc_html($job->updated_at);?> UTC</td><td><?php if('failed'===$job->state):?><form action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post"><?php wp_nonce_field('ae_retry_job');?><input type="hidden" name="action" value="ae_retry_job"><input type="hidden" name="job_id" value="<?php echo esc_attr($job->id);?>"><button class="button button-small">Tentar novamente</button></form><?php endif;?></td></tr><?php endforeach;if(!$jobs):?><tr><td colspan="7">Fila vazia.</td></tr><?php endif;?></tbody></table><?php return(string)ob_get_clean(); }
	private function elections(bool $counts=false): array { global $wpdb;$p=$wpdb->prefix.'ae_';return $counts?$wpdb->get_results("SELECT e.*,COUNT(c.id) contests FROM {$p}elections e LEFT JOIN {$p}contests c ON c.election_id=e.id GROUP BY e.id ORDER BY e.year DESC"):$wpdb->get_results("SELECT * FROM {$p}elections ORDER BY year DESC"); } // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
	private function election_select(string $name,array $elections): void { ?><label>Eleição<select name="<?php echo esc_attr($name);?>" required><option value="">Selecione...</option><?php foreach($elections as $e):?><option value="<?php echo esc_attr($e->id);?>"><?php echo esc_html($e->name);?></option><?php endforeach;?></select></label><?php }
	private function run_button(): void { ?><form class="ae-inline" action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post"><?php wp_nonce_field('ae_run_jobs');?><input type="hidden" name="action" value="ae_run_jobs"><button class="button">Processar fila agora</button></form><?php }
	private function notice(): void { if(empty($_GET['ae_notice']))return;$type='error'===($_GET['ae_type']??'')?'notice-error':'notice-success';echo '<div class="notice '.esc_attr($type).' is-dismissible"><p>'.esc_html(sanitize_text_field(wp_unslash($_GET['ae_notice']))).'</p></div>'; } // phpcs:ignore WordPress.Security.NonceVerification.Recommended
	private function redirect(string $tab,string $message,string $type='success'): never { wp_safe_redirect(add_query_arg(array('page'=>self::PAGE,'tab'=>$tab,'ae_notice'=>$message,'ae_type'=>$type),admin_url('admin.php')));exit; }
	private function verify(string $action): void { $this->guard();check_admin_referer($action); }
	private function guard(): void { if(!current_user_can('manage_options'))wp_die(esc_html__('Você não tem permissão para gerenciar a apuração.','tse-apuracao')); }
	private function url(string $tab): string { return add_query_arg(array('page'=>self::PAGE,'tab'=>$tab),admin_url('admin.php')); }
	private function state_label(string $state): string { return array('queued'=>'Na fila','running'=>'Processando','retry'=>'Nova tentativa','completed'=>'Concluído','failed'=>'Falhou')[$state]??$state; }
	private function ufs(): array { return array('AC'=>'Acre','AL'=>'Alagoas','AP'=>'Amapá','AM'=>'Amazonas','BA'=>'Bahia','CE'=>'Ceará','DF'=>'Distrito Federal','ES'=>'Espírito Santo','GO'=>'Goiás','MA'=>'Maranhão','MT'=>'Mato Grosso','MS'=>'Mato Grosso do Sul','MG'=>'Minas Gerais','PA'=>'Pará','PB'=>'Paraíba','PR'=>'Paraná','PE'=>'Pernambuco','PI'=>'Piauí','RJ'=>'Rio de Janeiro','RN'=>'Rio Grande do Norte','RS'=>'Rio Grande do Sul','RO'=>'Rondônia','RR'=>'Roraima','SC'=>'Santa Catarina','SP'=>'São Paulo','SE'=>'Sergipe','TO'=>'Tocantins'); }
}
